# 1. Data Load:

In [150]:
import pandas as pd

moviess = pd.read_csv("../data/movies_metadata.csv", low_memory=False)
credits = pd.read_csv("../data/credits.csv")
keywords = pd.read_csv("../data/keywords.csv")

# 2. Data Preprocessing :

### 1. For Movies:

In [151]:
moviess.shape
moviess.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [152]:
df_1 =moviess.drop(['homepage', 'adult','original_title','belongs_to_collection','vote_count','imdb_id', 'release_date', 'tagline', 'video','revenue','runtime', 'status','budget', 'poster_path', 'production_companies', 'production_countries'], axis=1)
df_1.columns.tolist()

['genres',
 'id',
 'original_language',
 'overview',
 'popularity',
 'spoken_languages',
 'title',
 'vote_average']

In [153]:
df_1.isnull().sum()

genres                 0
id                     0
original_language     11
overview             954
popularity             5
spoken_languages       6
title                  6
vote_average           6
dtype: int64

In [154]:
# as we can not able to add movie itself so from around 50k   to remove 950 rows is completely fine and we can drop those rows
df_1.dropna(inplace=True)
df_1.isnull().sum()
df_1.shape

(44496, 8)

### 2. credits

In [155]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  object
 1   crew    45476 non-null  object
 2   id      45476 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.0+ MB

In [156]:
credits.isnull().sum()

cast    0
crew    0
id      0
dtype: int64

In [157]:
credits.shape

(45476, 3)

In [158]:
credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

### 3. Keywords

In [159]:
keywords.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [160]:
keywords.isnull().sum()

id          0
keywords    0
dtype: int64

In [161]:
keywords.shape

(46419, 2)

### 4. Final Data set

In [162]:
print(df_1['id'].dtype)

object

In [163]:
df_1['id'] = df_1['id'].astype('int64')
credits['id'] = credits['id'].astype('int64')
keywords['id'] = keywords['id'].astype('int64')

In [164]:
movies = (
    df_1
    .merge(credits, on='id')
    .merge(keywords, on='id')
)

print(movies.shape)
movies.head()

(45619, 11)

,genres,id,original_language,overview,popularity,spoken_languages,title,vote_average,cast,crew,keywords
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'iso_639_1': 'en', 'name': 'English'}]",Toy Story,7.7,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,en,When siblings Judy and Peter discover an encha...,17.015539,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Jumanji,6.9,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,en,A family wedding reignites the ancient feud be...,11.7129,"[{'iso_639_1': 'en', 'name': 'English'}]",Grumpier Old Men,6.5,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,"[{'iso_639_1': 'en', 'name': 'English'}]",Waiting to Exhale,6.1,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,"[{'id': 35, 'name': 'Comedy'}]",11862,en,Just when George Banks has recovered from his ...,8.387519,"[{'iso_639_1': 'en', 'name': 'English'}]",Father of the Bride Part II,5.7,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."

In [165]:
movies = movies.iloc[:5000].reset_index(drop=True)

print(movies.shape)

(5000, 11)

In [166]:
## Convert string to Python list :: Extract only useful names

### 5.Extracting :

In [167]:
movies[["genres","spoken_languages","cast","crew","keywords"]].head(1)

,genres,spoken_languages,cast,crew,keywords
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","[{'iso_639_1': 'en', 'name': 'English'}]","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."

In [168]:
import ast
ast.literal_eval(movies['genres'].iloc[0])

def extract_names(text):
    L = []

    for item in ast.literal_eval(text):
        L.append(item['name'])

    return L

In [169]:
movies['genres'] = movies['genres'].apply(extract_names)

In [170]:
movies['genres'].head()

0     [Animation, Comedy, Family]
1    [Adventure, Fantasy, Family]
2               [Romance, Comedy]
3        [Comedy, Drama, Romance]
4                        [Comedy]
Name: genres, dtype: object

#### .....

In [171]:
ast.literal_eval(movies['keywords'].iloc[0])

movies['keywords'] = movies['keywords'].apply(extract_names)

In [172]:
movies['keywords'].head()

0    [jealousy, toy, boy, friendship, friends, riva...
1    [board game, disappearance, based on children'...
2    [fishing, best friend, duringcreditsstinger, o...
3    [based on novel, interracial relationship, sin...
4    [baby, midlife crisis, confidence, aging, daug...
Name: keywords, dtype: object

In [173]:
def extract_cast(text):
    L = []

    for item in ast.literal_eval(text)[:3]:
        L.append(item['name'])

    return L

#### ....

In [174]:
ast.literal_eval(movies['cast'].iloc[0])
movies['cast'] = movies['cast'].apply(extract_cast)

In [175]:
movies["cast"].head()

0                  [Tom Hanks, Tim Allen, Don Rickles]
1       [Robin Williams, Jonathan Hyde, Kirsten Dunst]
2           [Walter Matthau, Jack Lemmon, Ann-Margret]
3    [Whitney Houston, Angela Bassett, Loretta Devine]
4           [Steve Martin, Diane Keaton, Martin Short]
Name: cast, dtype: object

#### ....

In [176]:
ast.literal_eval(movies['spoken_languages'].iloc[0])
movies['spoken_languages'] = movies['spoken_languages'].apply(extract_names)

In [177]:
movies['spoken_languages'].head()

0              [English]
1    [English, Français]
2              [English]
3              [English]
4              [English]
Name: spoken_languages, dtype: object

#### ....

In [178]:
def fetch_director(text):
    for item in ast.literal_eval(text):
        if item['job'] == 'Director':
            return item['name']
    return None

In [179]:
ast.literal_eval(movies['crew'].iloc[0])
movies['crew']= movies['crew'].apply(fetch_director)

In [180]:
movies[['genres','keywords','cast','crew']].head()

,genres,keywords,cast,crew
0,"[Animation, Comedy, Family]","[jealousy, toy, boy, friendship, friends, riva...","[Tom Hanks, Tim Allen, Don Rickles]",John Lasseter
1,"[Adventure, Fantasy, Family]","[board game, disappearance, based on children'...","[Robin Williams, Jonathan Hyde, Kirsten Dunst]",Joe Johnston
2,"[Romance, Comedy]","[fishing, best friend, duringcreditsstinger, o...","[Walter Matthau, Jack Lemmon, Ann-Margret]",Howard Deutch
3,"[Comedy, Drama, Romance]","[based on novel, interracial relationship, sin...","[Whitney Houston, Angela Bassett, Loretta Devine]",Forest Whitaker
4,[Comedy],"[baby, midlife crisis, confidence, aging, daug...","[Steve Martin, Diane Keaton, Martin Short]",Charles Shyer

# VERSION 1

In [181]:
# movies['title'].dtype
# movies['overview'].dtype
movies['genres'].dtype
# movies['keywords'].dtype
# movies['cast'].dtype

dtype('O')

In [182]:
movies["overview"] = movies["overview"].apply(lambda x:x.split())         # list
movies["overview"] = movies["overview"].apply(
    lambda x: [i.lower() for i in x])


movies['crew'] = movies['crew'].apply(lambda x: [x])                           
movies['crew'] = movies['crew'].apply(
    lambda x: [i.lower().replace(" ", "") for i in x if isinstance(i, str)]     # list
)

movies['title'] = movies['title'].apply(        # string
    lambda x: x[0] if isinstance(x, list) else x
)

movies['cast'] = movies['cast'].apply(                                         # list
    lambda x:[i.lower().replace(" ", "") for i in x ] )

movies['genres'] = movies['genres'].apply(                                     # list
    lambda x: [i.lower() for i in x ]
)

In [183]:
version_1 = movies[['title','overview','genres','keywords','cast','crew']]

In [184]:
version_1.head()

,title,overview,genres,keywords,cast,crew
0,Toy Story,"[led, by, woody,, andy's, toys, live, happily,...","[animation, comedy, family]","[jealousy, toy, boy, friendship, friends, riva...","[tomhanks, timallen, donrickles]",[johnlasseter]
1,Jumanji,"[when, siblings, judy, and, peter, discover, a...","[adventure, fantasy, family]","[board game, disappearance, based on children'...","[robinwilliams, jonathanhyde, kirstendunst]",[joejohnston]
2,Grumpier Old Men,"[a, family, wedding, reignites, the, ancient, ...","[romance, comedy]","[fishing, best friend, duringcreditsstinger, o...","[waltermatthau, jacklemmon, ann-margret]",[howarddeutch]
3,Waiting to Exhale,"[cheated, on,, mistreated, and, stepped, on,, ...","[comedy, drama, romance]","[based on novel, interracial relationship, sin...","[whitneyhouston, angelabassett, lorettadevine]",[forestwhitaker]
4,Father of the Bride Part II,"[just, when, george, banks, has, recovered, fr...",[comedy],"[baby, midlife crisis, confidence, aging, daug...","[stevemartin, dianekeaton, martinshort]",[charlesshyer]

In [185]:
print(type(version_1['genres'].iloc[0]))
print(type(version_1['keywords'].iloc[0]))
print(type(version_1['cast'].iloc[0]))
print(type(version_1['crew'].iloc[0]))
print(type(version_1['overview'].iloc[0]))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>

In [186]:
version_1['title'].dtype

dtype('O')

In [187]:
version_1['title'] = version_1['title'].apply(
    lambda x: [x.lower().replace(" ", "")]
)

C:\Users\YASH RAJ\AppData\Local\Temp\ipykernel_46296\1455463078.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  version_1['title'] = version_1['title'].apply(

In [188]:
version_1['tags'] = (
    version_1['title']
    + version_1['overview']
    + version_1['genres']
    + version_1['keywords']
    + version_1['cast']
    + version_1['crew']
)

C:\Users\YASH RAJ\AppData\Local\Temp\ipykernel_46296\1798921088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  version_1['tags'] = (

In [189]:
version_1['tags'].iloc[0]

['toystory',
 'led',
 'by',
 'woody,',
 "andy's",
 'toys',
 'live',
 'happily',
 'in',
 'his',
 'room',
 'until',
 "andy's",
 'birthday',
 'brings',
 'buzz',
 'lightyear',
 'onto',
 'the',
 'scene.',
 'afraid',
 'of',
 'losing',
 'his',
 'place',
 'in',
 "andy's",
 'heart,',
 'woody',
 'plots',
 'against',
 'buzz.',
 'but',
 'when',
 'circumstances',
 'separate',
 'buzz',
 'and',
 'woody',
 'from',
 'their',
 'owner,',
 'the',
 'duo',
 'eventually',
 'learns',
 'to',
 'put',
 'aside',
 'their',
 'differences.',
 'animation',
 'comedy',
 'family',
 'jealousy',
 'toy',
 'boy',
 'friendship',
 'friends',
 'rivalry',
 'boy next door',
 'new toy',
 'toy comes to life',
 'tomhanks',
 'timallen',
 'donrickles',
 'johnlasseter']

In [190]:
version_1["tags"].value_counts()

tags
[thepromise, east-berlin,, 1961,, shortly, after, the, erection, of, the, wall., konrad,, sophie, and, three, of, their, friends, plan, a, daring, escape, to, western, germany., the, attempt, is, successful,, except, for, konrad,, who, remains, behind., from, then, on,, and, for, the, next, 28, years,, konrad, and, sophie, will, attempt, to, meet, again,, in, spite, of, the, iron, curtain., konrad,, who, has, become, a, reputed, astrophysicist,, tries, to, take, advantage, of, scientific, congresses, outside, eastern, germany, to, arrange, encounters, with, sophie., but, in, a, country, where, the, political, police,, the, stasi,, monitors, the, moves, of, all, suspicious, people, (such, as, konrad's, sister, ...]                                      8
[afarewelltoarms, british, nurse, catherine, barkley, (helen, hayes), and, american, lieutenant, frederic, henry, (gary, cooper), fall, in, love, during, the, first, world, war, in, italy., eventually, separated, by, frederic's, transfer,, tremendous, challenges, and, difficult, decisions, face, each,, as, the, war, rages, on., academy, awards, winner, for, best, cinematography, and, for, best, sound,, recording., nominated, for, best, picture, and, for, best, art, direction., drama, romance, war, italy, nurse, love letter, officer, priest, escape, hospital, best friend, pre-code, air raid, ambulance driver, battle of the isonzo, air attack, helenhayes, garycooper, adolphemenjou, frankborzage]                                                           4
[wife, ten, years, into, a, marriage,, the, wife, is, disappointed, by, the, husband's, lack, of, financial, success,, meaning, she, has, to, work, and, can't, treat, herself, and, the, husband, finds, the, wife, slovenly, and, mean-spirited:, she, neither, cooks, not, cleans, particularly, well, and, is, generally, disagreeable., in, turn,, he, alternately, ignores, her, and, treats, her, as, a, servant., neither, is, particularly, happy,, not, helped, by, their, unsatisfactory, lodgers., the, husband, is, easily, seduced, by, an, ex-colleague,, a, widow, with, a, small, child, who, needs, some, security,, and, considers, leaving, his, wife., drama, based on novel, wife, marriage, unhappiness, miekotakamine, kenuehara, rentarômikuni, mikionaruse]    4
[aplaceatthetable, using, personal, stories,, this, powerful, documentary, illuminates, the, plight, of, the, 49, million, americans, struggling, with, food, insecurity., a, single, mother,, a, small-town, policeman, and, a, farmer, are, among, those, for, whom, putting, food, on, the, table, is, a, daily, battle., documentary, woman director, jeffbridges, tomcolicchio, marianachilton, kristijacobson]                                                                                                                                                                                                                                                                                                                                                                     4
[pokémon:spelloftheunknown, when, molly, hale's, sadness, of, her, father's, disappearance, get, to, her,, she, unknowingly, uses, the, unown, to, create, her, own, dream, world, along, with, entei,, who, she, believes, to, be, her, father., when, entei, kidnaps, ash's, mom,, ash, along, with, misty, &, brock, invade, the, mansion, looking, for, his, mom, and, trying, to, stop, the, mysteries, of, molly's, dream, world, and, entei!, adventure, fantasy, animation, action, family, mountain, mountain village, friendship, based on tv series, young boy, pokémon, best friend, fighting, based on video game, pikachu, anime, veronicataylor, rachaellillis, ericstuart, michaelhaigney]                                                                               4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ..
[thedeadlymantis, the, calving, of, an, arctic, iceberg, releases, a, giant, praying, mantis,, trapped, in, suspended, animation, since, prehistoric, times., it, first, attacks, military, outposts, to, eat, their, occupants,, then, makes, its, way, to, the, warmer, latitudes, of, washington, and, new, york., a, paleontologist, works, together, with, military, units, to, try, to, kill, it., (copied, from, imdb), thriller, horror, romance, science fiction, monster, paleontology, paleontologist, arctic, giant monster, new york city, giant insect, man eating monster, prehistoric creature, mantis, praying mantis, insect, craigstevens, williamhopper, alixtalton, nathanh.juran]                                                                                  1
[dragonfly, a, grieving, doctor, is, being, contacted, by, his, late, wife, through, his, patients, near, death, experiences., drama, pregnancy and birth, voice, dragonfly, car crash, jungle, hospital, doctor, humanitarian, spiritism, kevincostner, joemorton, ronrifkin, tomshadyac]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
[queenofthedamned, lestat, de, lioncourt, is, awakened, from, his, slumber., bored, with, his, existence, he, has, now, become, this, generations, new, rock, god., while, in, the, course, of, time,, another, has, arisen,, akasha,, the, queen, of, the, vampires, and, the, dammed., he, want's, immortal, fame,, his, fellow, vampires, want, him, eternally, dead, for, his, betrayal,, and, the, queen, want's, him, for, her, king., who, will, be, the, first, to, reach, him?, who, shall, win?, drama, fantasy, horror, queen, rock star, secret society, vampire, light, bite, music, spontaneous combustion, fatal attraction, fang vamp, stuarttownsend, aaliyah, margueritemoreau, michaelrymer]                                                                          1
[bigbadlove, vietnam, veteran, leon, barlow, is, struggling, as, a, writer,, and, his, personal, life, isn't, much, better., his, unsympathetic, ex-wife, marilyn, doesn't, approve, of, his, visits, with, his, two, children,, and, he, has, problems, with, alcohol., yet, even, when, leon, manages, to, catch, up, on, alimony, and, child, support, payments,, things, in, his, life, seem, to, decline, further,, until, a, sudden, tragedy, catches, him, off, guard., drama, comedy, arlisshoward, debrawinger, paullemat, arlisshoward]                                                                                                                                                                                                                                        1
[greendragon, a, tale, about, vietnamese, refugees, sent, to, an, orientation, camp, on, the, camp, pendleton, marine, base, in, california,, 'green, dragon', focuses, on, a, young, boy, and, his, sister., set, in, 1975,, the, film, chronicles, the, stories, told, to, the, two, children, by, other, refugees, in, the, camp, and, of, tai, tran,, who, dares, to, introduce, himself, to, sergeant, jim, lance., in, developing, a, relationship, with, lance,, tran, is, able, to, improve, action, adventure, drama, independent film, patrickswayze, forestwhitaker, đơndương, timothylinhbui]                                                                                                                                                                                1
Name: count, Length: 4978, dtype: int64

In [191]:
version_1['tags'] = version_1['tags'].apply(lambda x: " ".join(x))   # BACK TO STR (as need in the stemmer

C:\Users\YASH RAJ\AppData\Local\Temp\ipykernel_46296\1349275226.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  version_1['tags'] = version_1['tags'].apply(lambda x: " ".join(x))   # BACK TO STR (as need in the stemmer

In [192]:
version_1['tags'].iloc[0]

"toystory led by woody, andy's toys live happily in his room until andy's birthday brings buzz lightyear onto the scene. afraid of losing his place in andy's heart, woody plots against buzz. but when circumstances separate buzz and woody from their owner, the duo eventually learns to put aside their differences. animation comedy family jealousy toy boy friendship friends rivalry boy next door new toy toy comes to life tomhanks timallen donrickles johnlasseter"

### Stemmer

In [193]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [194]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

def stem(text):
    y = []

    for word in text.split():
        y.append(ps.stem(word))

    return " ".join(y)

In [195]:
version_1['tags'] = version_1['tags'].apply(stem)

C:\Users\YASH RAJ\AppData\Local\Temp\ipykernel_46296\641001573.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  version_1['tags'] = version_1['tags'].apply(stem)

### CountVectorizer

In [196]:
# Keep only first 5000 movies
movies = movies.iloc[:5000].reset_index(drop=True)

print(movies.shape)

(5000, 11)

In [197]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(
    max_features=5000,
    stop_words='english'
)

vectors = cv.fit_transform(version_1['tags']).toarray()

print(vectors.shape)

(5000, 5000)

In [198]:
vectors.shape

(5000, 5000)

## THE Heart

In [199]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [200]:
similarity.shape

(5000, 5000)

In [201]:
def recommend(movie):

    movie_index = movies[
        movies['title'].str.lower() == movie.lower()
    ].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:8]

    for i in movies_list:
        print(movies.iloc[i[0]].title)

In [202]:
print("movies:", movies.shape)
print("version_1:", version_1.shape)
print("similarity:", similarity.shape)

movies: (5000, 11)
version_1: (5000, 7)
similarity: (5000, 5000)

In [203]:
print(movies['title'].head(20))

0                          Toy Story
1                            Jumanji
2                   Grumpier Old Men
3                  Waiting to Exhale
4        Father of the Bride Part II
5                               Heat
6                            Sabrina
7                       Tom and Huck
8                       Sudden Death
9                          GoldenEye
10            The American President
11       Dracula: Dead and Loving It
12                             Balto
13                             Nixon
14                  Cutthroat Island
15                            Casino
16             Sense and Sensibility
17                        Four Rooms
18    Ace Ventura: When Nature Calls
19                       Money Train
Name: title, dtype: object

In [204]:
movies[movies['title'].str.contains("Juman", case=False, na=False)]

,genres,id,original_language,overview,popularity,spoken_languages,title,vote_average,cast,crew,keywords
1,"[adventure, fantasy, family]",8844,en,"[when, siblings, judy, and, peter, discover, a...",17.015539,"[English, Français]",Jumanji,6.9,"[robinwilliams, jonathanhyde, kirstendunst]",[joejohnston],"[board game, disappearance, based on children'..."

In [205]:
print(movies['title'].dtype)

object

In [206]:
recommend("toy story")

Toy Story 2
Small Soldiers
Toys
Child's Play 2
The Indian in the Cupboard
The Million Dollar Duck
Brighton Beach Memoirs

## Saving Model

In [207]:
from joblib import dump

dump(movies, 'movies.joblib')

dump(similarity, 'similarity_1.joblib')

['similarity_1.joblib']

# VERSION 2

In [208]:
version_2 = version_1[["title",'overview','genres',"keywords","cast","crew"]]
version_2['spoken_languages'] = movies['spoken_languages']

In [209]:
version_2.head()

,title,overview,genres,keywords,cast,crew,spoken_languages
0,[toystory],"[led, by, woody,, andy's, toys, live, happily,...","[animation, comedy, family]","[jealousy, toy, boy, friendship, friends, riva...","[tomhanks, timallen, donrickles]",[johnlasseter],[English]
1,[jumanji],"[when, siblings, judy, and, peter, discover, a...","[adventure, fantasy, family]","[board game, disappearance, based on children'...","[robinwilliams, jonathanhyde, kirstendunst]",[joejohnston],"[English, Français]"
2,[grumpieroldmen],"[a, family, wedding, reignites, the, ancient, ...","[romance, comedy]","[fishing, best friend, duringcreditsstinger, o...","[waltermatthau, jacklemmon, ann-margret]",[howarddeutch],[English]
3,[waitingtoexhale],"[cheated, on,, mistreated, and, stepped, on,, ...","[comedy, drama, romance]","[based on novel, interracial relationship, sin...","[whitneyhouston, angelabassett, lorettadevine]",[forestwhitaker],[English]
4,[fatherofthebridepartii],"[just, when, george, banks, has, recovered, fr...",[comedy],"[baby, midlife crisis, confidence, aging, daug...","[stevemartin, dianekeaton, martinshort]",[charlesshyer],[English]

In [210]:
version_2['tags'] = (version_2['title']
                    + version_2['overview']
                    +  version_2['keywords']
                    +  version_2['cast'] 
                    +  version_2['crew']
	                +  version_2['spoken_languages']
                    +   version_2['genres']
)

In [211]:
version_2['tags'].iloc[0]

['toystory',
 'led',
 'by',
 'woody,',
 "andy's",
 'toys',
 'live',
 'happily',
 'in',
 'his',
 'room',
 'until',
 "andy's",
 'birthday',
 'brings',
 'buzz',
 'lightyear',
 'onto',
 'the',
 'scene.',
 'afraid',
 'of',
 'losing',
 'his',
 'place',
 'in',
 "andy's",
 'heart,',
 'woody',
 'plots',
 'against',
 'buzz.',
 'but',
 'when',
 'circumstances',
 'separate',
 'buzz',
 'and',
 'woody',
 'from',
 'their',
 'owner,',
 'the',
 'duo',
 'eventually',
 'learns',
 'to',
 'put',
 'aside',
 'their',
 'differences.',
 'jealousy',
 'toy',
 'boy',
 'friendship',
 'friends',
 'rivalry',
 'boy next door',
 'new toy',
 'toy comes to life',
 'tomhanks',
 'timallen',
 'donrickles',
 'johnlasseter',
 'English',
 'animation',
 'comedy',
 'family']

In [212]:
version_2['tags'] = version_2['tags'].apply(
    lambda x: " ".join(x)
)

In [213]:
from nltk.stem.porter import PorterStemmer

ps_2 = PorterStemmer()

def stem_2(text):
    y_2 =[]

    for word in text.split() :
        y_2.append(ps_2.stem(word))

    return " ".join(y_2)   



version_2['tags'] = version_2['tags'].apply(stem)

In [214]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(
    max_features=5000,
    stop_words='english'
)

vectors = cv.fit_transform(version_2['tags']).toarray()

print(vectors.shape)

(5000, 5000)

In [215]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_2 = cosine_similarity(vectors) 
def recommend_2(movie):

    movie_index = movies[
        movies['title'].str.lower() == movie.lower()
    ].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in movies_list:
        print(movies.iloc[i[0]].title)

In [216]:
version_1['title'].iloc[:20]

0                       [toystory]
1                        [jumanji]
2                 [grumpieroldmen]
3                [waitingtoexhale]
4         [fatherofthebridepartii]
5                           [heat]
6                        [sabrina]
7                     [tomandhuck]
8                    [suddendeath]
9                      [goldeneye]
10          [theamericanpresident]
11       [dracula:deadandlovingit]
12                         [balto]
13                         [nixon]
14               [cutthroatisland]
15                        [casino]
16           [senseandsensibility]
17                     [fourrooms]
18    [aceventura:whennaturecalls]
19                    [moneytrain]
Name: title, dtype: object

In [217]:
movies[movies['original_language'] != 'en'][['title','original_language']].head(20)

                          title original_language
28    The City of Lost Children                fr
29               Shanghai Triad                zh
51                     Lamerica                it
56                  The Postman                it
57             The Confessional                fr
66                 French Twist                fr
71               Les Miserables                fr
78            The White Balloon                fa
80               Antonia's Line                nl
94                     La Haine                fr
103             Nobody Loves Me                de
109         Rumble in the Bronx                cn
120           Chungking Express                cn
121              The Star Maker                it
124  The Silences of the Palace                ar
128           Frankie Starlight                it
130                   Nueba Yol                es
150               Belle de Jour                fr
195  The Umbrellas of Cherbourg                fr
209            Burnt by the Sun                ru

In [218]:
recommend("The City of Lost Children")

Rocket Gibraltar
Final Fantasy: The Spirits Within
Jimmy Neutron: Boy Genius
Village of the Damned
Mad Max Beyond Thunderdome
Children Underground
The Sexual Life of the Belgians

In [219]:
recommend_2('The City of Lost Children')

Rocket Gibraltar
Final Fantasy: The Spirits Within
Jimmy Neutron: Boy Genius
Village of the Damned
Mad Max Beyond Thunderdome

In [220]:
from joblib import dump

dump(similarity_2, 'similarity_2.joblib')

['similarity_2.joblib']

# VERSION 3

In [221]:
version_3 = version_2.drop(['tags'] , axis = 1)

In [222]:
version_3.head()

,title,overview,genres,keywords,cast,crew,spoken_languages
0,[toystory],"[led, by, woody,, andy's, toys, live, happily,...","[animation, comedy, family]","[jealousy, toy, boy, friendship, friends, riva...","[tomhanks, timallen, donrickles]",[johnlasseter],[English]
1,[jumanji],"[when, siblings, judy, and, peter, discover, a...","[adventure, fantasy, family]","[board game, disappearance, based on children'...","[robinwilliams, jonathanhyde, kirstendunst]",[joejohnston],"[English, Français]"
2,[grumpieroldmen],"[a, family, wedding, reignites, the, ancient, ...","[romance, comedy]","[fishing, best friend, duringcreditsstinger, o...","[waltermatthau, jacklemmon, ann-margret]",[howarddeutch],[English]
3,[waitingtoexhale],"[cheated, on,, mistreated, and, stepped, on,, ...","[comedy, drama, romance]","[based on novel, interracial relationship, sin...","[whitneyhouston, angelabassett, lorettadevine]",[forestwhitaker],[English]
4,[fatherofthebridepartii],"[just, when, george, banks, has, recovered, fr...",[comedy],"[baby, midlife crisis, confidence, aging, daug...","[stevemartin, dianekeaton, martinshort]",[charlesshyer],[English]

In [223]:
for col in ['overview','genres','keywords','cast','crew']:
    print(
        col,
        version_3[col].apply(len).mean()
    )

overview 54.1156
genres 2.4054
keywords 6.4642
cast 2.9356
crew 0.9944

In [224]:
# overview = 1x

version_3['genres'] = version_3['genres'].apply(
    lambda x: x * 5
)

version_3['keywords'] = version_3['keywords'].apply(
    lambda x: x * 5
)

version_3['cast'] = version_3['cast'].apply(
    lambda x: x * 3
)

version_3['crew'] = version_3['crew'].apply(
    lambda x: x * 2
)

version_3['spoken_languages'] = version_3[
    'spoken_languages'
].apply(
    lambda x: x * 5
)

In [225]:
version_3['tags'] = (
      version_3['title']
    + version_3['overview']
    + version_3['genres']
    + version_3['keywords']
    + version_3['cast']
    + version_3['crew']
    + version_3['spoken_languages']
)

In [226]:
version_3['tags'] = version_3['tags'].apply(
    lambda x: " ".join(x)
)
version_3['tags'] = version_3['tags'].apply(stem)

In [227]:
version_3['tags'].head()

0    toystori led by woody, andy' toy live happili ...
1    jumanji when sibl judi and peter discov an enc...
2    grumpieroldmen a famili wed reignit the ancien...
3    waitingtoexhal cheat on, mistreat and step on,...
4    fatherofthebridepartii just when georg bank ha...
Name: tags, dtype: object

In [228]:
from sklearn.feature_extraction.text import CountVectorizer

cv_3 = CountVectorizer(
    max_features=5000,
    stop_words='english'
)

vectors_3 = cv_3.fit_transform(
    version_3['tags']
).toarray()

In [229]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_3 = cosine_similarity(vectors_3)

In [230]:
def recommend_3(movie):

    movie_index = movies[
        movies['title'].str.lower() == movie.lower()
    ].index[0]

    distances = similarity_3[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:9]

    for i in movies_list:
        print(movies.iloc[i[0]].title)

In [231]:
from joblib import dump
dump(similarity_3 , "similarity_3.joblib")

['similarity_3.joblib']

In [232]:
recommend('The City of Lost Children')

Rocket Gibraltar
Final Fantasy: The Spirits Within
Jimmy Neutron: Boy Genius
Village of the Damned
Mad Max Beyond Thunderdome
Children Underground
The Sexual Life of the Belgians

In [233]:
recommend_2('Toy story')

Toy Story 2
Small Soldiers
Toys
Child's Play 2
The Indian in the Cupboard

In [234]:
recommend_3('Toy story')

Small Soldiers
Toy Story 2
Child's Play 2
Pinocchio
Babes in Toyland
Bride of Chucky
The Indian in the Cupboard
The Transformers: The Movie

# FINAL VERSION

In [235]:
# Final model uses Version 3
similarity_final = similarity_3

In [236]:
def recommend_final(movie):

    movie_index = movies[
        movies['title'].str.lower() == movie.lower()
    ].index[0]

    distances = similarity_final[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:9]

    recommendations = []

    for i in movies_list:
        recommendations.append(
            movies.iloc[i[0]].title
        )

    return recommendations

In [237]:
from joblib import dump
dump(similarity_final,"similarity_final.joblib")

['similarity_final.joblib']

In [ ]:
recommend("toy story")    #first version

Toy Story 2
Small Soldiers
Toys
Child's Play 2
The Indian in the Cupboard
The Million Dollar Duck
Brighton Beach Memoirs

In [ ]:
recommend_final('toy story')        # final version

['Small Soldiers',
 'Toy Story 2',
 "Child's Play 2",
 'Pinocchio',
 'Babes in Toyland',
 'Bride of Chucky',
 'The Indian in the Cupboard',
 'The Transformers: The Movie']